#!/bin/sh /etc/rc.common
START=90
USE_PROCD=1

service_triggers(){
	procd_add_reload_trigger 'n2n-supernode'
}

start_service(){
	[ "$(uci -q get n2n-supernode.@base[0].enabled)" = 0 ] && return 1
	port=$(uci -q get n2n-supernode.@base[0].port) || return 1
	community=$(uci -q get n2n-supernode.@base[0].community | sed "s/' '/\n/g" | sed "s/'//g")
	subnet=$(uci -q get n2n-supernode.@base[0].subnet)
	param="-Mfp $port"
	if [ -n "$community" ];then
		echo "$community" > /tmp/n2n-supernode.list
		param="$param -c /tmp/n2n-supernode.list"
	fi
	if [ -n "$subnet" ];then
		param="$param -a $subnet"
	fi
	procd_open_instance
	procd_set_param command /usr/bin/supernode $param
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param respawn
	procd_close_instance
}

stop_service(){
	rm -f /tmp/n2n-supernode.list
}

reload_service(){
	stop
	start
}
