#!/bin/sh /etc/rc.common
START=50

N=cpufreq
P=/sys/devices/system/cpu/$N
Q=$P/policy

uci_get_by_type(){
	z=$(uci -q get $N.@settings[0].$1)
	echo ${z:=$2}
}

start(){
	for i in $(find $Q* -maxdepth 0 | grep -Eo [0-9]+);do
		a=$(uci_get_by_type mode$i)
		[ $a ] || return
		echo $a > $Q$i/scaling_governor
		uci_get_by_type min$i > $Q$i/scaling_min_freq
		uci_get_by_type max$i > $Q$i/scaling_max_freq
		if [ $a = ondemand ];then
			uci_get_by_type rate$i 10 > $P/ondemand/sampling_down_factor
			uci_get_by_type up$i 50 > $P/ondemand/up_threshold
		fi
	done
}
