#!/bin/sh /etc/rc.common
START=25

add_arp()
{
	[ "$1" -a "$2" -a "$3" ] || return
	echo "Adding ARP:IP Addr:$1  MAC Addr:$2  Interface:$3"
	ip neigh replace $1 lladdr $2 nud permanent dev $3
}

arpconf()
{
	config_get ipaddr "$1" 'ipaddr'
	config_get macaddr "$1" 'macaddr'
	config_get ifname "$1" 'ifname'
	add_arp $ipaddr $macaddr $ifname
}

start()
{
	config_load 'arpbind'
	config_foreach arpconf 'arpbind'
}

stop()
{
	for i in $(ip neigh show | grep PERMANENT | sed 's/ /,/g');do
		ip neigh del $(echo $i | awk -F, '{print $1}') dev $(echo $i | awk -F, '{print $3}')
	done
}
