#!/bin/sh
a=$(ls /sys/class/net | grep eth | grep -v '\.')
b=$(echo "$a" | wc -l)
S=[
for i in $(seq 1 $b);do
	h='{"name":'
	c=$(echo "$a" | sed -n ${i}p)
	d=$(ethtool $c)
	e=$(echo "$d" | grep "Link detected" | awk -F: '{printf $2}' | sed 's/^[ \t]*//g')
	[ $e = yes ] && l=1 || l=0
	f=$(echo "$d" | grep "Speed" | awk -F: '{printf $2}' | sed 's/^[ \t]*//g' | tr -d "Unknown!")
	[ -z "$f" ] && f=-
	g=$(echo "$d" | grep "Duplex" | awk -F: '{printf $2}' | sed 's/^[ \t]*//g')
	[ "$g" = Full ] && x=1 || x=0
	S="$S$h \"$c\", \"status\": $l, \"speed\": \"$f\", \"duplex\": $x},"
done
S=${S%,*};S=$S];echo $S
